### PR TITLE
Try to automatically find and remember the path to Nightly

### PR DESCRIPTION
**Pull request by mythmon**
This should work for all three of us, and be easy for others to get into to. The idea is that it should either figure it out, or ask you once and not bug you again after that.

@tiftran I'm especially interested if this works for you on OSX.

r?

### CODE REVIEW

**Review by rehandalal — DISMISSED** [review]
this looks awesome, thanks!! 👏🏽

**Review by tiftran — COMMENTED** [review]
erm it wasn't too happy with me 
```
$ webpack --progress --mode development --watch
/Users/tiffanytran/Desktop/normandy-devtools/bin/find-nightly.sh: line 9: conditional binary operator expected
$ /Users/tiffanytran/Desktop/normandy-devtools/node_modules/.bin/web-ext run --firefox '' -s dist
Applying config files: ./package.json, ./web-ext-config.js

```

**Comment by rehandalal** [comment]
ah! for me it's because mine is `firefox-nightly` not `nightly`.

**Comment by rehandalal** [comment]
Running `which firefox-nightly > .nightly-path` got this working.

**Comment by mythmon** [comment]
> Running `which firefox-nightly > .nightly-path` got this working.

Weird, the script is supposed to ask to do that. I'll look into this more tomorrow.

**Comment by rehandalal** [comment]
I suspect running the script outside of yarn would have made that happen

**Comment by mythmon** [comment]
The intended way this gets used, and the way I was testing it, is to just run `yarn watch:extension` (or `yarn watch`, but lets take this one step at a time).

I also don't expect it to actually automatically find Nightly for either of you, I expect it to ask for a path and then remember it. Basically, it should automate the thing that Rehan did by echoing a path into `.nightly-path`.

I pushed a change that should be more compatible with OSX. Lets see how this does.

**Comment by mythmon** [comment]
The intended way this gets used, and the way I was testing it, is to just run `yarn watch:extension` (or `yarn watch`, but lets take this one step at a time).

I also don't expect it to actually automatically find Nightly for either of you, I expect it to ask for a path and then remember it. Basically, it should automate the thing that Rehan did by echoing a path into `.nightly-path`.

I pushed a change that should be more compatible with OSX. Lets see how this does.

**Review by tiftran — COMMENTED** [review]
was able to set WEB_EXT_BROWSER as an env var and get it to start up.
But when I don't, and I try to input my path at the prompt it gives me 

```
* Type the full path to an installation of Firefox Nightly and press enter.
  This will be stored in /Users/tiffanytran/Desktop/normandy-devtools/.nightly-p
ath and remembered for the future.

* Press ctrl-c to exit this script and set the environment variable
  $WEB_EXT_BROWSER to a path to Nightly. Then re-run this command.

* Press ctrl-c to exit this script and make a command 'nightly' available on
  your PATH. This will be used automatically.

> /Users/tiffanytran/Applications/"Firefox Nightly 2.app"/Contents/MacOS/firefox-bin
> 
/Users/tiffanytran/Desktop/normandy-devtools/bin/find-nightly.sh: line 49: : command not found
```
Not sure if this is a me, not understanding problem?

**Comment by rehandalal** [comment]
Thanks for the work on this but I'm gonna close in favor of #95 which should solve the issue for most people

**Pull request closed without merging**
