### PR TITLE
Make UI consistent and decluttering for details page

### PR DESCRIPTION
**Pull request by rehandalal**
this PR does a few things:
- corrects some visual inconsistencies on the details page
  - add subtle text color to field values in approval request and experimenter section
  - fix some margins
- re-orders experimenter details section and approval request section
- declutters the recipe details page header by moving the experimenter and telemetry links
  - links are now in the menu under the ellipsis button
  - links also in the header of experimenter details section
  - links also in the panel of the experimenter details section
- converts a few more `.js` files to `.tsx`

r?

### CODE REVIEW

**Comment by rehandalal** [comment]
### Before:
image

### After:
image

**Comment by mythmon** [comment]
Experimenter detail views that include branch information (like multi-pref-experiments) now have inconsistent font weight, since the branch descriptions aren't subtle.

image

**Comment by mythmon** [comment]
```
  ● TelemetryLink › should includes dates for complete experiments

    ReferenceError: IconButton is not defined

      44 |   }
      45 | 
    > 46 |   let Component = IconButton;
         |                   ^
      47 |   let extraProps: TelemetryLinkExtraProps = {
      48 |     icon: <Icon icon="bar-chart" />,
      49 |   };

      at TelemetryLink (content/components/recipes/details/TelemetryLink.tsx:46:19)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14803:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17482:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:18596:16)
```

**Review by mythmon — CHANGES_REQUESTED** [review]
I like the UI changes. A couple little things, and some weird test failure to contend with.

**Comment by rehandalal** [comment]
Fixed the branches styling:
image

Still trying to work out the test weirdness

**Comment by rehandalal** [comment]
I can't figure out this `IconButton` issue in the tests. It doesn't happen locally.

**Pull request merged**
