### PR TITLE
When listing recipes, use fixed size cards instead of expanding ones

### LINKED ISSUE #381: Remove recipe quick-view on listing page
The recipe expando on the listing page was ok when it was the only thing available, but now that we have a proper detail page it really just gets in the way.

I'd be ok with having a better designed quick-view that isn't just "mythmon tossed the data into a yaml formatter" in the future.

### PR DESCRIPTION
**Pull request by mythmon**
- [x] Fix alignment when titles are too long
- [x] Fix tests

### Actions menu
image

### Wide screen
image

### Narrow screen
image

Depends on #378

Fixes #381

### CODE REVIEW

**Comment by mythmon** [comment]
@rehandalal f?

**Comment by jaredlockhart** [comment]
Looks great!

**Comment by mythmon** [comment]
After some updates, the cards now look like this:
image

**Review by rehandalal — APPROVED** [review]
lets merge this now and i'll iterate in a later PR

bors r+

**Comment by mythmon** [comment]
I'll fix up the merge conflict.

**Comment by mythmon** [comment]
bors r= @rehandalal

**Pull request merged**
