### PR TITLE
hide run buttons for web

### LINKED ISSUE #415: Hide run buttons in web-mode
Running recipes needs extension super powers which we won't have in web-mode. We should hide all run buttons, including custom run, in web-mode.

### PR DESCRIPTION
**Pull request by tiftran**
fixes #415

### CODE REVIEW

**Review by mythmon — COMMENTED** [review]
This looks like it would work well.

One thing I've been pondering is if we should have some higher order component for this and other conditional display stuff. Maybe like 

```js
<OnlyIf extension>
  <Dropdown.Item onSelect={this.handleRunButtonClick}>
  ...
</OnlyIf>
```

I'm not sure if that would work as well with Webpack's dead code removal though, so maybe not. Though I'm not sure if dead code removal even works in JSX in the first place. What do you think about that?

Also, I noticed this is marked as a draft. What else were you planning to change here?

**Comment by tiftran** [comment]
I had left it on draft since I was missing tests. Having a high order component, this would mean hiding the 
the if `__ENV__ === "extension"` logic into a component right?

**Comment by mythmon** [comment]
> Having a high order component, this would mean hiding the the if `__ENV__ === "extension"` logic into a component right?

Right. Also to be clear I'm asking for feedback about this idea, with the possibility of someone eventually implementing it. I'm not saying we should block this PR on adding that feature (unless you want to do it that way).

**Comment by tiftran** [comment]
>  Also to be clear I'm asking for feedback about this idea, with the possibility of someone eventually implementing it

I was planning/hoping to probably pick up #414 next, maybe I'll let this idea sit with me while doing that?

Given the above, I think this PR is ready to be reviewed

**Review by mythmon — APPROVED** [review]
Sounds like a good plan.

bors r+

**Pull request merged**
