### PR TITLE
Calculate a testing client ID for bucket samples filters

### PR DESCRIPTION
**Pull request by mythmon**
I wanted to implement this in a place where I could re-use use instead of in Firefox's console.

It ends up looking like this:

image

### CODE REVIEW

**Review by rehandalal — DISMISSED** [review]
very cool!

needs tests though.

**Comment by mythmon** [comment]
Finally got tests that pass for this, and have high enough coverage. That was a bit tougher than I expected.

@tiftran Can you review this now, since Rehan is out?

**Review by tiftran — APPROVED** [review]
Looks good to me, and thank you for correcting my typo :)

**Pull request merged**
