### PR TITLE
Use -f nightly flag with web-ext

### PR DESCRIPTION
**Pull request by rehandalal**
r?

### CODE REVIEW

**Review by mythmon — APPROVED** [review]
This is correct, but now we don't need to run the two commands in separate terminals, as `yarn watch` should just work. I'm not sure if this a better workflow or not (I haven't tried it). It might be worth only mentioning `yarn watch`, or softening the language of running the command in separate terminals.

Or we could leave it as it is now, your call.

bors delegate+

**Comment by rehandalal** [comment]
I only use the `yarn watch` workflow and it works well for me. Although I think there's room for a little bit of improvement because it does a double build to start which is a little annoying.

**Review by rehandalal — COMMENTED** [review]
bors r=@mythmon

**Comment by mythmon** [comment]
> I only use the `yarn watch` workflow and it works well for me. Although I think there's room for a little bit of improvement because it does a double build to start which is a little annoying.

That's actually by design. `webpack --watch` will build do a build first, and then start watching. There isn't a way to wait for that first build to finish though, and we need to make sure there is some build before starting web-ext. So `yarn watch` runs a normal build first, and then starts both webpack and web-ext in watch mode in parallel.

There has been [an open issue for Webpack](https://github.com/webpack/webpack/issues/4991) for a long time to give it an option to watch but not build, and it would solve this exact case. There is even a PR for it, but it hasn't been merged.

Is the double build actually slowing you down, or just wasteful? I wonder if we could make the second build basically a no-op if we tweak the caching or some other options.

**Comment by rehandalal** [comment]
It's not really slowing me down at most times. It's just if I'm making certain kind of changes like to the webpack config where I need to restart it can sometimes be annoying. I'm not too concerned about it.

**Comment by mythmon** [comment]
Ah, ok. The second build doesn't block the extension starting, it's just noise. The first build, which is blocking in your case, is needed anyways. And watch mode rebuilds seem pretty quick to me. So the double build isn't making anything worse.

It sounds like there might be some small benefit in trying to optimize our build times, but it's not a big deal.

**Pull request merged**
